language: haskell

env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2
 - GHCVER=head

matrix:
  fast_finish: true
  allow_failures:
   - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy-1.19.3
 - cabal update

install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
 - export PATH=/opt/happy/1.19.3/bin:/opt/ghc/$GHCVER/bin:$PATH
 - cabal --version
 - cabal install -j --enable-tests --enable-benchmarks --only-dependencies

script:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test --show-details=always
 - cabal check
 - cabal sdist
